TOTAL NO OF MALE PARTICIPATES

SELECT SUM(MALE) FROM PROJECT.DATASET;

TOTAL NO OF FEMALE PARTICIPATES

SELECT SUM(FEMALE) FROM PROJECT.DATASET;

GENDER RATIO

SELECT SUM(FEMALE)/SUM(MALE) FROM PROJECT.DATASET

