STARTUPS HAVING ATLEAST ONE FEMALE


SELECT SUM(A.FEMALE COUNT)STARTUPS HAVING AT LEAST WOMEN FROM(
SELECT FEMALE.CASE WHEN FEMALE>0 THEN 1 ELSE 0 END AS FEMALE_COUNT FROM PROJECT.DATASET;

SELECT SUM(A.FEMALE_COUNT) AS `Startups with at least one woman`
FROM (
    SELECT CASE 
        WHEN `Female` > 0 THEN 1 
        ELSE 0 
    END AS FEMALE_COUNT 
    FROM `project`.`dataset`
) A;

